# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskAI = channel.unary_unary(
                '/ai.AIService/AskAI',
                request_serializer=ai__pb2.AIRequest.SerializeToString,
                response_deserializer=ai__pb2.AIResponse.FromString,
                _registered_method=True)
        self.ProcessQuery = channel.unary_stream(
                '/ai.AIService/ProcessQuery',
                request_serializer=ai__pb2.ProcessQueryRequest.SerializeToString,
                response_deserializer=ai__pb2.ProcessQueryResponse.FromString,
                _registered_method=True)
        self.EmbedMessage = channel.unary_unary(
                '/ai.AIService/EmbedMessage',
                request_serializer=ai__pb2.EmbedMessageRequest.SerializeToString,
                response_deserializer=ai__pb2.EmbedMessageResponse.FromString,
                _registered_method=True)
        self.SeedChats = channel.unary_unary(
                '/ai.AIService/SeedChats',
                request_serializer=ai__pb2.SeedChatsRequest.SerializeToString,
                response_deserializer=ai__pb2.SeedChatsResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskAI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeedChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskAI': grpc.unary_unary_rpc_method_handler(
                    servicer.AskAI,
                    request_deserializer=ai__pb2.AIRequest.FromString,
                    response_serializer=ai__pb2.AIResponse.SerializeToString,
            ),
            'ProcessQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessQuery,
                    request_deserializer=ai__pb2.ProcessQueryRequest.FromString,
                    response_serializer=ai__pb2.ProcessQueryResponse.SerializeToString,
            ),
            'EmbedMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedMessage,
                    request_deserializer=ai__pb2.EmbedMessageRequest.FromString,
                    response_serializer=ai__pb2.EmbedMessageResponse.SerializeToString,
            ),
            'SeedChats': grpc.unary_unary_rpc_method_handler(
                    servicer.SeedChats,
                    request_deserializer=ai__pb2.SeedChatsRequest.FromString,
                    response_serializer=ai__pb2.SeedChatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/AskAI',
            ai__pb2.AIRequest.SerializeToString,
            ai__pb2.AIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.AIService/ProcessQuery',
            ai__pb2.ProcessQueryRequest.SerializeToString,
            ai__pb2.ProcessQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/EmbedMessage',
            ai__pb2.EmbedMessageRequest.SerializeToString,
            ai__pb2.EmbedMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeedChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/SeedChats',
            ai__pb2.SeedChatsRequest.SerializeToString,
            ai__pb2.SeedChatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
