# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"\x1b\n\tAIRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1e\n\nAIResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"D\n\x0b\x43hatMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\"4\n\x0cGroupDetails\x12\x10\n\x08group_id\x18\x01 \x01(\x03\x12\x12\n\ngroup_name\x18\x02 \x01(\t\"\x88\x01\n\x13ProcessQueryRequest\x12\x1f\n\x05group\x18\x01 \x01(\x0b\x32\x10.ai.GroupDetails\x12\x1e\n\x05\x63hats\x18\x02 \x03(\x0b\x32\x0f.ai.ChatMessage\x12\r\n\x05query\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x10\n\x08username\x18\x05 \x01(\t\"(\n\x14ProcessQueryResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x8c\x01\n\x13\x45mbedMessageRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x11\n\tsender_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x10\n\x08is_group\x18\x06 \x01(\x08\"6\n\x14\x45mbedMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"]\n\x10SeedChatsRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x10\n\x08is_group\x18\x02 \x01(\x08\x12\x1e\n\x05\x63hats\x18\x03 \x03(\x0b\x32\x0f.ai.ChatMessage\"5\n\x11SeedChatsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf5\x01\n\tAIService\x12&\n\x05\x41skAI\x12\r.ai.AIRequest\x1a\x0e.ai.AIResponse\x12\x43\n\x0cProcessQuery\x12\x17.ai.ProcessQueryRequest\x1a\x18.ai.ProcessQueryResponse0\x01\x12\x41\n\x0c\x45mbedMessage\x12\x17.ai.EmbedMessageRequest\x1a\x18.ai.EmbedMessageResponse\x12\x38\n\tSeedChats\x12\x14.ai.SeedChatsRequest\x1a\x15.ai.SeedChatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIREQUEST']._serialized_start=16
  _globals['_AIREQUEST']._serialized_end=43
  _globals['_AIRESPONSE']._serialized_start=45
  _globals['_AIRESPONSE']._serialized_end=75
  _globals['_CHATMESSAGE']._serialized_start=77
  _globals['_CHATMESSAGE']._serialized_end=145
  _globals['_GROUPDETAILS']._serialized_start=147
  _globals['_GROUPDETAILS']._serialized_end=199
  _globals['_PROCESSQUERYREQUEST']._serialized_start=202
  _globals['_PROCESSQUERYREQUEST']._serialized_end=338
  _globals['_PROCESSQUERYRESPONSE']._serialized_start=340
  _globals['_PROCESSQUERYRESPONSE']._serialized_end=380
  _globals['_EMBEDMESSAGEREQUEST']._serialized_start=383
  _globals['_EMBEDMESSAGEREQUEST']._serialized_end=523
  _globals['_EMBEDMESSAGERESPONSE']._serialized_start=525
  _globals['_EMBEDMESSAGERESPONSE']._serialized_end=579
  _globals['_SEEDCHATSREQUEST']._serialized_start=581
  _globals['_SEEDCHATSREQUEST']._serialized_end=674
  _globals['_SEEDCHATSRESPONSE']._serialized_start=676
  _globals['_SEEDCHATSRESPONSE']._serialized_end=729
  _globals['_AISERVICE']._serialized_start=732
  _globals['_AISERVICE']._serialized_end=977
# @@protoc_insertion_point(module_scope)
