# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"\x1b\n\tAIRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1e\n\nAIResponse\x12\x10\n\x08response\x18\x01 \x01(\t23\n\tAIService\x12&\n\x05\x41skAI\x12\r.ai.AIRequest\x1a\x0e.ai.AIResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIREQUEST']._serialized_start=16
  _globals['_AIREQUEST']._serialized_end=43
  _globals['_AIRESPONSE']._serialized_start=45
  _globals['_AIRESPONSE']._serialized_end=75
  _globals['_AISERVICE']._serialized_start=77
  _globals['_AISERVICE']._serialized_end=128
# @@protoc_insertion_point(module_scope)
